# Generated by Django 3.0.3 on 2020-02-22 01:35

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campos.Categoria')),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campos.Classificacao')),
                ('operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campos.Operacao')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sistema')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campos.Subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Grupos Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(max_length=300)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conhecimento.GrupoConhecimento')),
            ],
            options={
                'verbose_name_plural': 'Conhecimentos',
            },
        ),
    ]
