# Generated by Django 3.0.3 on 2020-02-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('ativo', models.BooleanField()),
                ('cadastrado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=70)),
                ('numero', models.CharField(max_length=10)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade')),
            ],
            options={
                'verbose_name_plural': 'Ramais',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('razao_social', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado')], max_length=20)),
                ('cadastrado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sistema')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
