# Generated by Django 3.0.3 on 2020-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('sistema', models.ManyToManyField(to='core.Sistema')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Classificacoes',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('categoria', models.ManyToManyField(to='campos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('classificacao', models.ManyToManyField(to='campos.Classificacao')),
            ],
            options={
                'verbose_name_plural': 'Operacoes',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('pendencia', models.BooleanField()),
                ('campo', models.BooleanField()),
                ('encerrado', models.BooleanField()),
                ('unidade', models.ManyToManyField(to='core.Unidade')),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='classificacao',
            name='subcategoria',
            field=models.ManyToManyField(to='campos.Subcategoria'),
        ),
    ]
