# Generated by Django 3.0.3 on 2020-02-22 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=50)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Categoria')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Classificacao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Estado')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Operacao')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Subcategoria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('interagido_em', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
            options={
                'verbose_name_plural': 'Interacoes',
            },
        ),
    ]
